# Generated by Django 4.2 on 2023-04-22 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('caption', models.TextField(blank=True, max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Craeted oN')),
                ('reminder', models.DateField(blank=True, verbose_name='Reminder')),
                ('attachment', models.FileField(upload_to='base/attachments')),
            ],
        ),
    ]
