# Generated by Django 4.2 on 2023-04-22 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='base/attachments'),
        ),
    ]
