# Generated by Django 4.2 on 2023-04-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_todo_owner_alter_todo_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='mark',
            field=models.CharField(choices=[('FIRE', '🔥'), ('WARNING', '⚠️'), ('EXLAMATION', '❗')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
