# Generated by Django 4.2 on 2023-04-27 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_todo_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='mark',
            field=models.CharField(choices=[('Fire', '🔥'), ('Warning', '⚠️')], max_length=15),
        ),
    ]
