# Generated by Django 4.2.1 on 2023-06-09 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_todo_mark_alter_todo_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='attachment',
        ),
    ]
