# Generated by Django 4.2.1 on 2023-06-12 16:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0007_remove_todo_attachment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='Task',
        ),
    ]
