# Generated by Django 4.2.1 on 2023-06-18 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_todo_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-id']},
        ),
    ]
