# Generated by Django 4.2.1 on 2023-06-19 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0009_alter_task_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Craeted on'),
        ),
        migrations.CreateModel(
            name='SharredTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.task')),
                ('users', models.ManyToManyField(blank=True, related_name='sharred', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
