# Generated by Django 4.2.1 on 2023-06-19 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_task_created_on_sharredtask'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sharredtask',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='sharredtask',
            name='name',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
