# Generated by Django 4.2.1 on 2023-07-03 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_sharredtask_options_sharredtask_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharredtask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='app.task'),
        ),
    ]
