# Generated by Django 4.2.1 on 2023-07-07 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_alter_sharredtask_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharredtask',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Craeted on'),
        ),
        migrations.AddField(
            model_name='sharredtask',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
