# Generated by Django 4.2.1 on 2023-07-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_sharredtask_created_on_sharredtask_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharredtask',
            name='task',
        ),
    ]
