# Generated by Django 4.2.1 on 2023-07-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_sharredtask_task'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharredtask',
            name='task',
        ),
        migrations.AddField(
            model_name='sharredtask',
            name='task',
            field=models.ManyToManyField(related_name='task', to='app.task'),
        ),
    ]
