# Generated by Django 4.2.1 on 2023-07-28 13:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0016_remove_sharredtask_task_sharredtask_task'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SharredTask',
            new_name='SharedTask',
        ),
    ]
