# Generated by Django 4.2.1 on 2023-08-05 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_sharredtask_sharedtask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminder',
        ),
    ]
