# Generated by Django 4.2.1 on 2023-08-08 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_task_reminder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharedtask',
            old_name='task',
            new_name='tasks',
        ),
    ]
