# Generated by Django 4.2.1 on 2023-07-28 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_customuser_followers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='followers',
        ),
    ]
